### ISSUE TITLE
Create helm chart for public use

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/helm_charts#94]
Hello team,

Please go ahead and create a helm chart for IsItUp and make sure it's available for everyone to deploy their cluster

Helm chart needs to be documented and softcoded 

Please watch following videos if you have any questions 
https://academy.fuchicorp.com/search/?name=waypoint&duration=&topic=

Thank you

**Comment by tutac** [comment]
We have a couple of questions.
1) We build the image but it doesn't work because it is using our GitHub organization set up in the image. What do we need to remove to make those work for the general public? The image is crashing currently.
2) We have general instructions ready but we will need to know more about the setup to put in .the README

**Comment by fsadykov** [comment]
Hello @tutac

Sorry I forgot to mention in the ticket please use following image for now
https://hub.docker.com/repository/docker/fsadykov/isitup

**Comment by tutac** [comment]
We are currently working on the ingress for proxy and without.  We were able to add a statement to have only proxy ingress, deployment, and service to activate when it's enabled.  We are unsure how to create a statement to disable the ingress (not proxy) when the proxy is enabled.  We also keep having a cookie error.  We have generated the cookie with the docker statement in the file and have cleared our browser cookies but it still errors.

**Comment by fsadykov** [comment]
For cookies you will need to leave to the client means on your `values.yaml` mention how to generate cookies
For ingress thing, you will need to make sure two ingresses configured which means you will need to create two if statements
first statement for regular ingress 
```
{{- if not .Values.proxy.ingress.enabled }}
{{- if .Values.ingress.enabled }}
...  put your regular ingress 
{{- end }}
{{- end }}
```

Second ingress configuration for proxy 
```
{{- if not .Values.ingress.enabled }}
{{- if .Values.proxy.ingress.enabled }}
...  put your proxy ingress def
{{- end }}
{{- end }}
```

**Comment by ksalrin** [comment]
Hi Farkhod!

We are trying to use your image on dockerhub for isitup and getting "Invalid Image".  Can you please let us know if this is the right image name "fsadykov/isitup"? 
https://hub.docker.com/r/fsadykov/isitup/tags?page=1&ordering=last_updated

**Comment by fuchicorp-manage** [comment]
We are moving this ticket to ready for demo. Since this ticket was assigned long time ago

**Comment by alimer08** [comment]
when trying to test the chart I encountered these errors
<img width="1512" alt="Screen Shot 2022-01-26 at 11 25 12 AM" src="https://user-images.githubusercontent.com/77550392/151216733-91d0130e-7f24-40ef-9c9b-95f65510b0c0.png">

and 
<img width="1512" alt="Screen Shot 2022-01-26 at 11 36 13 AM" src="https://user-images.githubusercontent.com/77550392/151216819-2b854026-3c72-4bbd-9e34-86bb4e01f051.png">

**Comment by fsadykov** [comment]
I have used following commands to deploy the isitup 
```
11708  helm upgrade isitup -n dev ./
11709  helm upgrade --install isitup -n dev ./
11710  helm uninstall -n dev isitup-dev
11711  helm upgrade --install isitup -n dev ./
11712  helm uninstall -n dev isitup-dev
11713  helm uninstall -n dev isitup
11714  clear
11715  k get ingress -n dev
11716  helm upgrade --install isitup -n dev ./
11717  k delete ingresses.extensions -n dev
11718  helm upgrade --install isitup -n dev ./
11719  k get ingress -n dev
11720  k get service -n dev
11721  k get pod -n dev
11722  k logs -n dev isitup-66d84d5449-7bkrx
11723  clear
11724  k get pod -n dev
╭─fsadykov@bastion-fuchicorp-com
```

**Comment by alimer08** [comment]
This is my [WIKI](https://github.com/fuchicorp/helm_charts/wiki/Create-IsItUp-helm-chart-for-public-use-%2394)
